/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

public class App {

    public static void main(String[] args) {
        Vetor v = new Vetor();
        v.adicionar(1);

        System.out.println(v);
        
    }
}
